### ISSUE TITLE
/usr/local/bin/twistd: Unknown command: restmq

### ISSUE THREAD

**Issue by ferdynice** [gleicon/restmq#14]
./start_scripts/restmq_server

results in output:

/usr/lib/python2.7/dist-packages/zope/**init**.py:3: UserWarning: Module twisted was already imported from /usr/lib/python2.7/dist-packages/twisted/**init**.pyc, but /usr/local/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
Usage: twistd [options]
Options:
      --savestats      save the Stats object rather than the text output of the
                       profiler.
  -o, --no_save        do not save state on shutdown
  -e, --encrypted      The specified tap/aos file is encrypted.
  -n, --nodaemon       don't daemonize, don't use default umask of 0077
**_cut**_
twistd reads a twisted.application.service.Application out of a file and runs
it.
Commands:
    dns              A domain name server.
    ftp              An FTP server.
    inetd            An inetd(8) replacement.
    manhole-old      An interactive remote debugger service.
    portforward      A simple port-forwarder.
    socks            A SOCKSv4 proxy service.
    telnet           A simple, telnet-based remote debugging service.
    web              A general-purpose web server which can serve from a
                     filesystem or application resource.

/usr/local/bin/twistd: Unknown command: restmq

This is on Mint14.

How is this possible?

**Comment by JulioSantanaR** [comment]
@fiorix Thanks!! This solution is very useful for a lot of things :)

**Comment by fiorix** [comment]
👍

**Comment by warmlight** [comment]
@fiorix 👍 Thanks!!~~~~~~
