### ISSUE TITLE
Ruby example incorrect

### ISSUE THREAD

**Issue by AlexRevin** [gleicon/restmq#19]
I have tried implementing the em-http-request poller, but the problem with it, is that if gets data in chunks from the stream, and in case there's a big json object stored in queue, em-http splits it into several chunks, causing JSON parse errors.

I was not able to find receive buffer setting in the gem itself, so I would appreciate if you had any suggestions.

**Comment by gleicon** [comment]
hm, long time I dont do ruby. Will look around but can't guarantee that as I think that's an internal EM decision.
