### ISSUE TITLE
GET to dequeue sounds dangerous

### ISSUE THREAD

**Issue by abstratt** [gleicon/restmq#21]
As I will be destroying data with a supposedly read-only verb.

Instead, could use a DELETE on a <queue>/head URI or something like that.

**Comment by gleicon** [comment]
I implemented a take/delete semantic in the /queue/ endpoint as it is. DELETE for a /q/ endpoint will purge the queue. I see where you are coming for but I implemented the semantics a bit differently based on queues, not messages. Thanks !

**Comment by abstratt** [comment]
@gleicon Right, that is why I suggested a different URI (/q/head for instance).

**Comment by gleicon** [comment]
I could use a pull request if you want to dig into this. RestMQ is really simple and the core redis engine has proper functions to delete messages. If you want to dig on it I'm up to assist, but it would probably take some time for me to implement it as I'm involved with other projects right now. Thanks !
